# Generated by Django 3.0.2 on 2020-05-05 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='labour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=50)),
                ('emp_id', models.IntegerField()),
                ('ot_hr', models.IntegerField()),
                ('holi_day', models.IntegerField()),
                ('sunday_hr', models.IntegerField()),
                ('Number_days', models.IntegerField()),
                ('basic_wages', models.IntegerField()),
                ('extra_wages', models.IntegerField()),
                ('travel_al', models.IntegerField()),
                ('sunday_wages', models.IntegerField()),
                ('incentive', models.IntegerField()),
                ('holi_wages', models.IntegerField()),
                ('final_wages', models.IntegerField()),
            ],
        ),
    ]
